config/routes.rb
Rails.application.routes.draw do
  resources :outage_reports do
    get 'service/:slug', action: :service, on: :collection, as: :service
  end
  resources :services
  resources :providers

  root 'welcome#index'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => [:slugged]
  validates_presence_of :name, uniqueness: true

  has_many :provider_services
  has_many :services, through: :provider_services

  accepts_nested_attributes_for :services

  def should_generate_new_friendly_id?
    !slug? || name_changed?
  end

  def to_s
    name
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :address, :phone, :email, service_ids: [])
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.haml
= simple_form_for(@provider) do |f|
  .input-fields
    = f.input :name
    = f.input :address
    = f.input :phone
    = f.input :email
    = f.association :services
  .actions.text-right
    = f.button :submit, class: 'btn btn-primary'

app/views/providers/_sidebar.html.haml
- content_for :sidebar do
  .panel.panel-default
    .panel-heading
      %h1.panel-title Providers
    .panel-body
      - if current_page?(providers_path)
        = link_to 'New', new_provider_path, class: 'btn btn-default btn-block'

      - if @provider && !@provider.new_record?
        - unless current_page? @provider
          = link_to 'View', @provider, class: 'btn btn-default btn-block'
        - unless current_page? edit_provider_path(@provider)
          = link_to 'Edit', edit_provider_path(@provider), class: 'btn btn-default btn-block'

      - unless current_page?(providers_path)
        = link_to providers_path, class: 'btn btn-default btn-block' do
          %i.fa.fa-arrow-left
          Back to providers list

app/views/providers/edit.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Editing provider
  .panel-body
    = render 'form'

= render 'sidebar'

app/views/providers/index.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Providers List
  %table.table
    %thead
      %tr
        %th Name
        %th Address
        %th Phone
        %th Email
        %th
    %tbody
      - @providers.each do |provider|
        %tr
          %td= provider.name
          %td= provider.address
          %td= provider.phone
          %td= provider.email
          %td.text-right
            .btn-group
              = link_to 'View', provider, class: 'btn btn-default'
              = link_to 'Edit', edit_provider_path(provider), class: 'btn btn-primary'
              = link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

= render 'sidebar'

app/views/providers/new.html.haml
%h1 New Provider
= render 'form'
= link_to 'Back', providers_path

app/views/providers/show.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title= @provider.name
  .panel-body
    %dl.dl-horizontal
      %dt Address:
      %dd{ style: 'white-space: pre-line;' }= @provider.address
      %dt Phone:
      %dd= @provider.phone
      %dt Email:
      %dd= @provider.email
      %dt Services:
      %dd= @provider.services.pluck(:name).join(', ')

= render 'sidebar'