config/routes.rb
Rails.application.routes.draw do
  resources :outage_reports do
    get 'service/:slug', action: :service, on: :collection, as: :service
  end
  resources :services
  resources :providers

  root 'welcome#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => [:slugged]
  validates_presence_of :name, uniqueness: true

  has_many :outage_reports

  def should_generate_new_friendly_id?
    !slug? || name_changed?
  end

  def to_s
    name
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :color)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.haml
= simple_form_for(@service) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :color, hint: '#RRGGBB', input_html: { data: { behavior: 'colorpicker' } }
  .form-actions.text-right
    = f.button :submit, class: 'btn btn-primary'

app/views/services/_sidebar.html.haml
- content_for :sidebar do
  .panel.panel-default
    .panel-heading
      %h1.panel-title Services
    .panel-body
      - if current_page?(services_path)
        = link_to 'New', new_service_path, class: 'btn btn-default btn-block'

      - if @service && !@service.new_record?
        - unless current_page? @service
          = link_to 'View', @service, class: 'btn btn-default btn-block'
        - unless current_page? edit_service_path(@service)
          = link_to 'Edit', edit_service_path(@service), class: 'btn btn-default btn-block'

      - unless current_page?(services_path)
        = link_to services_path, class: 'btn btn-default btn-block' do
          %i.fa.fa-arrow-left
          Back to services list

app/views/services/edit.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Editing service
  .panel-body
    = render 'form'

= render 'sidebar'

app/views/services/index.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Services list
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th # Outages
        %th
    %tbody
      - @services.each do |service|
        %tr
          %td
            %div{style: "display: inline-block; background-color: #{service.color}; height: 20px; width: 20px;"} &nbsp;
            = service.name
          %td
            .badge= service.outage_reports.size
          %td.text-right
            .btn-group
              = link_to 'View', service, class: 'btn btn-default'
              = link_to 'Edit', edit_service_path(service), class: 'btn btn-primary'
              = link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

= render 'sidebar'

app/views/services/new.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title New service
  .panel-body
    = render 'form'

= render 'sidebar'

app/views/services/show.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Service
  #map.half-screen
    %layer{ data: { type: 'geojson', url: service_outage_reports_path(slug: @service.name, format: :geojson) } }
      = render 'shared/popup'
  .panel-body
    %dl.dl-horizontal
      %dt Name:
      %dd
        = @service.name
      %dt Color:
      %dd
        %span{ style: "display: inline-block; background-color: #{@service.color}; height: 20px; width: 20px;"} &nbsp;

= render 'sidebar'