config/routes.rb
Rails.application.routes.draw do
  resources :outage_reports do
    get 'service/:slug', action: :service, on: :collection, as: :service
  end
  resources :services
  resources :providers

  root 'welcome#index'

end

app/models/outage_report.rb
class OutageReport < ActiveRecord::Base
  belongs_to :service
  belongs_to :provider

  validates :service_id, presence: true

  def wkt
    geometry
  end

  def geometry
    @geometry ||= GeoRuby::SimpleFeatures::Point.from_coordinates(location.split(', ').map(&:to_f).reverse)
  end
end

app/controllers/outage_reports_controller.rb
class OutageReportsController < ApplicationController
  before_action :set_outage_report, only: [:show, :edit, :update, :destroy]

  # GET /outage_reports
  # GET /outage_reports.json
  def index
    @outage_reports = OutageReport.all

    respond_to do |format|
      format.html
      format.json
      format.geojson
    end
  end

  def service
    respond_to do |format|
      format.html {
        @outage_report = OutageReport.new
        @layers = [{ type: 'geojson', url: service_outage_reports_path(params[:slug], :geojson) }]
        render layout: 'map'
      }
      format.geojson {
        @outage_reports = OutageReport.joins(:service).references(:service).where(services: { name: params[:slug] })
      }
    end
  end

  # GET /outage_reports/1
  # GET /outage_reports/1.json
  def show
    respond_to do |format|
      format.html
      format.geojson
      format.json
    end
  end

  # GET /outage_reports/new
  def new
    @outage_report = OutageReport.new
  end

  # GET /outage_reports/1/edit
  def edit
  end

  # POST /outage_reports
  # POST /outage_reports.json
  def create
    @outage_report = OutageReport.new(outage_report_params)

    respond_to do |format|
      if @outage_report.save
        format.html { redirect_to @outage_report, notice: 'Outage report was successfully created.' }
        format.json { render :show, status: :created, location: @outage_report }
      else
        format.html { render :new }
        format.json { render json: @outage_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outage_reports/1
  # PATCH/PUT /outage_reports/1.json
  def update
    respond_to do |format|
      if @outage_report.update(outage_report_params)
        format.html { redirect_to @outage_report, notice: 'Outage report was successfully updated.' }
        format.json { render :show, status: :ok, location: @outage_report }
      else
        format.html { render :edit }
        format.json { render json: @outage_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outage_reports/1
  # DELETE /outage_reports/1.json
  def destroy
    @outage_report.destroy
    respond_to do |format|
      format.html { redirect_to outage_reports_url, notice: 'Outage report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outage_report
      @outage_report = OutageReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outage_report_params
      params.require(:outage_report).permit(:service_id, :provider_id, :location, :address, :notes, :started_at, :ended_at)
    end
end

app/helpers/outage_reports_helper.rb
module OutageReportsHelper
end

app/views/outage_reports/_form.html.haml
= simple_form_for(@outage_report) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-sm-6
        = f.association :service, input_html: { data: { behavior: 'select2' } }
      .col-sm-6
        = f.association :provider
    = f.input :location
    = f.input :address
    = f.input :notes
    = f.input :started_at
  .form-actions
    .row
      .col-sm-6
        %button.btn.btn-default.btn-block{ type: 'button', data: { toggle: 'collapse', dismiss: 'modal', target: '#report-form' } }
          Cancel
      .col-sm-6
        = f.button :submit, class: 'btn btn-primary btn-block'

app/views/outage_reports/_sidebar.html.haml
- content_for :sidebar do
  .panel.panel-default
    .panel-heading
      %h1.panel-title Outage report
    .panel-body
      - if @outage_report && !@outage_report.new_record?
        - unless current_page? @outage_report
          = link_to 'View', @outage_report, class: 'btn btn-default btn-block'

      = link_to root_path, class: 'btn btn-default btn-block' do
        %i.fa.fa-arrow-left
        Back to outage reports

app/views/outage_reports/edit.html.haml
%h1 Editing Outage Report
= render 'form'
= link_to 'Show', @outage_report
|
= link_to 'Back', outage_reports_path

app/views/outage_reports/index.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Outage reports

  %table.table.table-striped
    %thead
      %tr
        %th Service
        %th Provider
        %th Location
        %th Address
        %th Notes
        %th Started at
        %th Ended at
        %th{:colspan => "3"}
    %tbody
      - @outage_reports.each do |outage_report|
        %tr
          %td= outage_report.service
          %td= outage_report.provider
          %td= outage_report.location
          %td= outage_report.address
          %td= outage_report.notes
          %td= outage_report.started_at
          %td= outage_report.ended_at
          %td= link_to 'Show', outage_report
          %td= link_to 'Edit', edit_outage_report_path(outage_report)
          %td= link_to 'Destroy', outage_report, method: :delete, data: { confirm: 'Are you sure?' }

= render 'sidebar'

app/views/outage_reports/new.html.haml
%h1 New Outage Report
= render 'form'
= link_to 'Back', outage_reports_path

app/views/outage_reports/service.html.haml
= render 'shared/map'
- content_for :title do
  \:: #{params[:slug]} services

app/views/outage_reports/show.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Outage report
  #map.half-screen
    %layer{ data: { type: 'geojson', url: outage_report_path(@outage_report, :geojson) } }
      = render 'shared/popup'
  .panel-body
    %dl.dl-horizontal
      %dt Service:
      %dd= @outage_report.service
      %dt Provider:
      %dd= @outage_report.provider
      %dt Location:
      %dd= @outage_report.location
      %dt Address:
      %dd{ style: 'white-space: pre-line;'}= @outage_report.address
      - if @outage_report.notes.present?
        %dt Notes:
        %dd= @outage_report.notes
      %dt Started at:
      %dd= @outage_report.started_at
      - if @outage_report.ended_at?
        %dt Ended at:
        %dd= @outage_report.ended_at

= render 'sidebar'