config/routes.rb
Rails.application.routes.draw do
  resources :outage_reports do
    get 'service/:slug', action: :service, on: :collection, as: :service
  end
  resources :services
  resources :providers

  root 'welcome#index'

end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type,msg|
  .alert{ class: "alert-#{bootstrap_flash_type(type)}" }
    %button.close{ data: { dismiss: 'alert' }} &times;
    = msg

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: 'collapse', target: '#navbar' }}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_url, class: 'navbar-brand' do
        Outta Powa
        = content_for :title

    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          = link_to '#manager-menu', data: { toggle: 'dropdown' } do
            Manager
            %span.caret
          %ul.dropdown-menu
            %li= link_to 'Providers', providers_path
            %li= link_to 'Services', services_path
        %li.dropdown
          = link_to '#filter-services', data: { toggle: 'dropdown' } do
            %i.fa.fa-fw.fa-search
            Filter by service
            %span.caret
          %ul.dropdown-menu
            %li= link_to 'All services', root_url
            - Service.find_each do |service|
              %li
                = link_to service_outage_reports_path(service.name) do
                  .pull-right.badge= service.outage_reports.size
                  %span{ style: "display: inline-block; background-color: #{service.color}; height: 20px; width: 20px;"} &nbsp;
                  = service.name

app/views/layouts/_two_columns.html.haml
.row
  .col-sm-4
    = content_for :sidebar
  .col-sm-8
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Outta Powa
    %script{:src => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css", :rel => "stylesheet"}/
    %script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css", :rel => "stylesheet"}/
    /[if lt IE 9]
      <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      - if content_for? :sidebar
        = render 'layouts/two_columns'
      - else
        = yield

app/views/layouts/map.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Outta Powa
    %script{:src => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css", :rel => "stylesheet"}/
    %script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css", :rel => "stylesheet"}/
    /[if lt IE 9]
      <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    = yield

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Utilityfeed
    %script{:src => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css", :rel => "stylesheet"}/
    %script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css", :rel => "stylesheet"}/
    /[if lt IE 9]
      <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>
      
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    = yield